swagger: '2.0'

info:
  title: API
  description: API
  version: 1.0.0

definitions:
  host:
    type: object
    properties:
      id:
        type: integer
      host:
        type: string
      port:
        type: string
      is_active:
        type: boolean
  user:
    type: object
    properties:
      id:
        type: integer
      login:
        type: string
